name: Python Unit Tests with Aggregation

on:
  ## https://docs.github.com/en/actions/reference/workflows-and-actions/events-that-trigger-workflows
  schedule:
    - cron: "0,5,10,15,20,25,30,35,40,45,50,55 * * * *" #
      timezone: "Asia/Tokyo"
  push:
    branches: [ "master" ] #
  pull_request:
    branches: [ "master" ] #

jobs:
  test:
    ## https://docs.github.com/en/actions/reference/runners/github-hosted-runners
    runs-on: ubuntu-24.04
    strategy:
      matrix:
        python-version: ['3.9', '3.10', '3.11']

    steps:
    - name: 準備/install uuid
      run: sudo apt-get -y install uuid

    - name: 準備/UUIDを発行
      run: uuid

    - name: 準備/テストメッセージ出力
      run: echo "Hello world!"

    - name: 準備/時間表示
      run: date

    - name: 準備/uname
      run: uname -a

    - name: 準備/pwd
      run: pwd

    - uses: actions/checkout@v3

    - name: 準備/ls
      run: ls -lasF

    - name: 準備/tree
      run: tree

    - name: 準備/Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}

    - name: 準備/pip
      run: pip install unittest-xml-reporting

    - run: python3 python/run.py
    - run: python3 python/tests/test_addtition.py -v

    - name: 後処理/tree
      run: tree

    - name: 後処理/find
      run: find . -type f -not -path './.git/*'

#    - name: Upload test results
#      if: always()
#      uses: actions/upload-artifact@v3
#      with:
#        name: test-results-${{ matrix.python-version }}
#        path: test-results.xml
#
#    - name: Publish test results to GitHub
#      if: always()
#      uses: EnricoMi/publish-unit-test-result-action@v2
#      with:
#        files: test-results.xml
#        check_name: Test Results (${{ matrix.python-version }})

