name: Python Unit Tests with Aggregation

on:
  ## https://docs.github.com/en/actions/reference/workflows-and-actions/events-that-trigger-workflows
  #schedule:
  #  - cron: '*/1 * * * *' # 1分ごとに実行
  push:
    branches: [ "master" ] #
  pull_request:
    branches: [ "master" ] #

jobs:
  test:
    ## https://docs.github.com/en/actions/reference/runners/github-hosted-runners
    runs-on: ubuntu-24.04
    steps:
    - run: echo "Hello world!"

